import PDFDocument from 'pdfkit';
import { Response } from 'express';

export class DocumentService {

    /**
     * Streams a PDF Placement Letter to the response
     */
    static generatePlacementLetter(
        res: Response,
        data: {
            studentName: string,
            companyName: string,
            jobTitle: string,
            startDate: string
        }
    ) {
        const doc = new PDFDocument({ margin: 50 });

        // Pipe to response
        doc.pipe(res);

        // Header
        doc.fontSize(20).text('OFFICIAL PLACEMENT OFFER', { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).text(new Date().toDateString(), { align: 'right' });
        doc.moveDown(2);

        // Body
        doc.fontSize(12).text(`Dear ${data.studentName},`);
        doc.moveDown();
        doc.text(`We are pleased to confirm your industrial attachment placement at ${data.companyName} for the position of ${data.jobTitle}.`);
        doc.moveDown();
        doc.text(`Your start date is scheduled for: ${data.startDate}.`);
        doc.moveDown();
        doc.text('This attachment is part of your curricular requirements. Please print this letter and present it on your first day.');
        doc.moveDown(2);

        // Footer
        doc.fontSize(10).fillColor('gray').text('Generated by SAPS (Student Attachment Placement System)', { align: 'center' });

        doc.end();
    }

    /**
     * Stubs a NITA Form (Simplified for Phase 2)
     */
    /**
     * Generates a formal NITA Industrial Attachment Form
     */
    static generateNITAForm(
        res: Response,
        data: {
            studentName: string,
            regNumber: string,
            course: string,
            institution: string,
            companyName: string,
            companyAddress: string,
            duration: string,
            startDate: string,
            endDate: string
        }
    ) {
        const doc = new PDFDocument({ margin: 40 });
        doc.pipe(res);

        // -- TITLE --
        doc.fontSize(16).font('Helvetica-Bold').text('NATIONAL INDUSTRIAL TRAINING AUTHORITY', { align: 'center' });
        doc.fontSize(12).text('INDUSTRIAL ATTACHMENT CONTRACT FORM', { align: 'center' });
        doc.moveDown(2);

        // -- PART A: STUDENT DETAILS --
        doc.rect(40, doc.y, 530, 25).fill('#e0e0e0').stroke();
        doc.fillColor('black').fontSize(12).text('PART A: STUDENT PARTICULARS', 50, doc.y - 18);
        doc.moveDown(1);

        let y = doc.y;
        doc.fontSize(10).font('Helvetica');
        doc.text(`Full Name: ${data.studentName}`, 50, y);
        doc.text(`Registration No: ${data.regNumber}`, 300, y);
        y += 20;
        doc.text(`Course of Study: ${data.course}`, 50, y);
        doc.text(`Institution: ${data.institution}`, 300, y);
        doc.moveDown(2);

        // -- PART B: COMPANY DETAILS --
        y = doc.y + 10;
        doc.rect(40, y, 530, 25).fill('#e0e0e0').stroke();
        doc.fillColor('black').fontSize(12).font('Helvetica-Bold').text('PART B: COMPANY / EMPLOYER DETAILS', 50, y + 7);

        y += 35;
        doc.fontSize(10).font('Helvetica');
        doc.text(`Company Name: ${data.companyName}`, 50, y);
        doc.text(`Address/Location: ${data.companyAddress}`, 300, y);
        y += 20;
        doc.text(`Supervisor Name: _______________________`, 50, y);
        doc.text(`Tel / Email: _______________________`, 300, y);
        doc.moveDown(2);

        // -- PART C: ATTACHMENT DETAILS --
        y = doc.y + 10;
        doc.rect(40, y, 530, 25).fill('#e0e0e0').stroke();
        doc.fillColor('black').fontSize(12).font('Helvetica-Bold').text('PART C: ATTACHMENT DURATION', 50, y + 7);

        y += 35;
        doc.fontSize(10).font('Helvetica');
        doc.text(`Period of Attachment: ${data.duration}`, 50, y);
        y += 20;
        doc.text(`From: ${data.startDate}`, 50, y);
        doc.text(`To: ${data.endDate}`, 300, y);
        doc.moveDown(3);

        // -- DECLARATION --
        y = doc.y + 10;
        doc.fontSize(10).font('Helvetica-Oblique');
        doc.text('I certify that the information given above is correct to the best of my knowledge.', 50, y);

        y += 40;
        doc.font('Helvetica');
        doc.text('Student Signature: _______________________', 50, y);
        doc.text('Date: _______________', 350, y);

        y += 40;
        doc.text('Employer Signature: ______________________', 50, y);
        doc.text('Stamp: _______________', 350, y);

        // Footer
        doc.fontSize(8).text('Generated by AISHA System - NITA Compliant', 50, 750, { align: 'center', width: 500 });

        doc.end();
    }
}
