from typing import List, Dict, Any, Optional
import numpy as np
from app.core.ml_factory import model_factory

def cos_sim(a, b):
    a = np.array(a)
    b = np.array(b)
    if a.ndim == 1 and b.ndim == 1:
        return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b) + 1e-9)
    if a.ndim == 1 and b.ndim == 2:
        return np.dot(b, a) / (np.linalg.norm(b, axis=1) * np.linalg.norm(a) + 1e-9)
    norm_a = np.linalg.norm(a, axis=1, keepdims=True)
    norm_b = np.linalg.norm(b, axis=1, keepdims=True)
    return np.dot(a, b.T) / (np.dot(norm_a, norm_b.T) + 1e-9)

class KnowledgeService:
    """
    RAG-based Knowledge Engine.
    Stores and retrieves system knowledge snippets semantically.
    """
    
    _instance = None
    _kb_embeddings = None

    def __new__(cls, *args, **kwargs):
        if not cls._instance:
            cls._instance = super(KnowledgeService, cls).__new__(cls)
            cls._instance._initialized = False
        return cls._instance

    def __init__(self):
        if getattr(self, '_initialized', False):
            return
            
        self.model = model_factory.get_model()
        # Knowledge Base: A collection of semantic snippets
        # In a real app, this would be backed by a Vector DB (e.g. Pinecone, Chroma)
        self.knowledge_base: List[Dict[str, Any]] = [
            {
                "id": "attachment_rules",
                "content": "Students must have accepted a placement offer before they can officially start. Placements are recorded on the secure ledger.",
                "tags": ["rules", "attachment", "ledger"]
            },
            {
                "id": "insurance_info",
                "content": "Personal Accident Insurance is mandatory for all students on attachment. SAPS provides an autonomous insurance micro-payment system via M-Pesa to cover this requirement.",
                "tags": ["insurance", "mpesa", "safety"]
            },
            {
                "id": "placement_letters",
                "content": "Placement letters are officially generated by AISHA once a company accepts a student and the student confirms the offer. These letters must be presented to the host company on day one.",
                "tags": ["documents", "letters", "acceptance"]
            },
            {
                "id": "matching_logic_v4",
                "content": "The AISHA matching algorithm uses a combination of Semantic Skill Alignment (45%), Career Interest (35%), and Location Proximity (20%). It is self-adaptive and improves as more matches are confirmed.",
                "tags": ["algorithm", "matching", "ai"]
            },
            {
                "id": "stipend_guidelines",
                "content": "While not all attachments offer stipends, the system allows companies to list stipend amounts. Students can filter for paid opportunities in the search dashboard.",
                "tags": ["stipend", "payment", "money"]
            },
            {
                "id": "system_overview",
                "content": "AISHA is an AI-powered system designed to automate the industrial attachment process. As a user support guide, the system helps students find placements, manage digital logbooks, and automatically generate necessary documents.",
                "tags": ["overview", "system", "guide", "purpose"]
            },
            {
                "id": "how_to_navigate",
                "content": "To navigate the system: The 'Dashboard' shows your active status. The 'Opportunities' tab lists available attachments you can apply for. The 'Logbook' tab is where you record your daily activities and submit them weekly for supervisor review. The 'Documents' section holds your verified files like insurance and placement letters.",
                "tags": ["navigate", "help", "tabs", "dashboard", "logbook"]
            },
            {
                "id": "common_questions",
                "content": "Common questions students ask: 1. How do I get an attachment? (Complete your profile, check 'Opportunities', and rely on our AI matching). 2. How do I fill my logbook? (Go to 'Logbook', fill in daily activities, and submit at the end of the week). 3. Is insurance mandatory? (Yes, you must have insurance before starting your placement). 4. How are matches made? (Based on a combination of your skills, academic grades, and career interests).",
                "tags": ["faq", "common", "questions", "help"]
            },
            {
                "id": "single_best_fit_and_window",
                "content": "The system uses a 'Single Best Fit' matching logic. When matched with an opportunity, students have a 24-hour preference window to either accept or decline the offer. If they do not act within 24 hours, the offer automatically expires and is passed to the next best candidate.",
                "tags": ["matching", "24-hour", "window", "preference", "timeout", "offer"]
            },
            {
                "id": "nita_forms_removal",
                "content": "AISHA does NOT use the outdated NITA forms. All references to NITA forms have been completely removed and replaced by our automated Cover Letter and Acceptance Letter generation systems.",
                "tags": ["nita", "forms", "cover letter", "acceptance letter", "automation"]
            },
            {
                "id": "system_architecture_gemini",
                "content": "The platform's primary AI architecture is powered by the cloud-based Google Gemini models. Mentions of Ollama are obsolete; Gemini handles reasoning, transcript extraction, matching analysis, and chatbot interactions.",
                "tags": ["architecture", "gemini", "ai", "ollama", "cloud"]
            },
            {
                "id": "portals_and_dashboards",
                "content": "AISHA has four main portals: 1. Student Portal (for applying and logging). 2. Company Portal (with an Opportunity Manager and Placement Tracker for supervisors). 3. Institution Portal (where university admins and department supervisors track students). 4. Admin Portal (for global system management).",
                "tags": ["portals", "company", "institution", "student", "admin", "dashboard"]
            },
            {
                "id": "digital_logbooks_workflow",
                "content": "Logbooks are entirely digital. Students fill out daily activities and submit a weekly summary. Industry supervisors sign off digitally via the Placement Tracker, and University supervisors follow up via the Institution portal. These digital logbooks can be exported as official PDF documents.",
                "tags": ["logbook", "pdf", "export", "supervisor", "digital", "signature"]
            },
            {
                "id": "creators_and_developers",
                "content": "The AISHA system was created by a dedicated team of students from Masinde Muliro University of Science and Technology (MMUST). The team includes Brian Ndinya as the Project Manager and Chief/Main Developer, alongside developers Obadiah Kipngetich, Emmanuel Muchina, and Joshua Kephas.",
                "tags": ["developers", "creators", "team", "mmust", "brian ndinya", "obadiah kipngetich", "emmanuel muchina", "joshua kephas", "project manager", "chief developer", "main developer"]
            }
        ]
        
        # Pre-compute embeddings for storage
        print("Pre-computing Knowledge Base embeddings...")
        self.kb_embeddings = self.model.encode(
            [item["content"] for item in self.knowledge_base]
        )
        self._initialized = True

    def query_knowledge(self, query: str, top_k: int = 2) -> List[Dict[str, Any]]:
        """
        Retrieves the most semantically relevant knowledge snippets for a query.
        """
        query_embedding = self.model.encode(query)
        
        # Compute cosine similarities
        cosine_scores = cos_sim(query_embedding, self.kb_embeddings)
        
        # Flatten and get top-k indices
        if isinstance(cosine_scores, np.ndarray) and cosine_scores.ndim > 1:
            cosine_scores = cosine_scores[0]
        elif isinstance(cosine_scores, list) and isinstance(cosine_scores[0], list):
            cosine_scores = cosine_scores[0]
        
        cosine_scores = np.array(cosine_scores)
        top_k = min(top_k, len(self.knowledge_base))
        top_indices = np.argsort(cosine_scores)[-top_k:][::-1]
        
        results = []
        for idx in top_indices:
            score = cosine_scores[idx]
            if score > 0.3: # Minimum relevance threshold
                results.append({
                    "snippet": self.knowledge_base[idx]["content"],
                    "confidence": round(float(score), 2),
                    "id": self.knowledge_base[idx]["id"]
                })
                
        return results

    def add_knowledge(self, content: str, tags: Optional[List[str]] = None) -> str:
        """
        [Autonomous Learning] Dynamically adds new information to the knowledge base.
        """
        import uuid
        uid_str: str = str(uuid.uuid4()).replace("-", "")
        new_id = f"dynamic_{uid_str[:8]}"
        self.knowledge_base.append({
            "id": new_id,
            "content": content,
            "tags": tags if tags is not None else []
        })
        # Re-compute embeddings (In Vector DB this happens automatically)
        self.kb_embeddings = self.model.encode(
            [item["content"] for item in self.knowledge_base]
        )
        return new_id
