from typing import List, Dict, Any, Optional
from sentence_transformers import util, SentenceTransformer
import torch
from app.core.ml_factory import model_factory

class KnowledgeService:
    """
    RAG-based Knowledge Engine.
    Stores and retrieves system knowledge snippets semantically.
    """
    
    _instance = None
    _kb_embeddings = None

    def __new__(cls, *args, **kwargs):
        if not cls._instance:
            cls._instance = super(KnowledgeService, cls).__new__(cls)
            cls._instance._initialized = False
        return cls._instance

    def __init__(self):
        if getattr(self, '_initialized', False):
            return
            
        self.model: SentenceTransformer = model_factory.get_model()
        # Knowledge Base: A collection of semantic snippets
        # In a real app, this would be backed by a Vector DB (e.g. Pinecone, Chroma)
        self.knowledge_base: List[Dict[str, Any]] = [
            {
                "id": "nita_rules",
                "content": "NITA (National Industrial Training Authority) requires all students to have a signed Industrial Attachment Contract Form before starting. The attachment period is typically 3 months.",
                "tags": ["nita", "regulations", "attachment"]
            },
            {
                "id": "insurance_info",
                "content": "Personal Accident Insurance is mandatory for all students on attachment. SAPS provides an autonomous insurance micro-payment system via M-Pesa to cover this requirement.",
                "tags": ["insurance", "mpesa", "safety"]
            },
            {
                "id": "placement_letters",
                "content": "Placement letters are officially generated by AISHA once a company accepts a student and the student confirms the offer. These letters must be presented to the host company on day one.",
                "tags": ["documents", "letters", "acceptance"]
            },
            {
                "id": "matching_logic_v4",
                "content": "The AISHA matching algorithm uses a combination of Semantic Skill Alignment (45%), Career Interest (35%), and Location Proximity (20%). It is self-adaptive and improves as more matches are confirmed.",
                "tags": ["algorithm", "matching", "ai"]
            },
            {
                "id": "stipend_guidelines",
                "content": "While not all attachments offer stipends, the system allows companies to list stipend amounts. Students can filter for paid opportunities in the search dashboard.",
                "tags": ["stipend", "payment", "money"]
            }
        ]
        
        # Pre-compute embeddings for storage
        print("Pre-computing Knowledge Base embeddings...")
        self.kb_embeddings = self.model.encode(
            [item["content"] for item in self.knowledge_base], 
            convert_to_tensor=True
        )
        self._initialized = True

    def query_knowledge(self, query: str, top_k: int = 2) -> List[Dict[str, Any]]:
        """
        Retrieves the most semantically relevant knowledge snippets for a query.
        """
        query_embedding = self.model.encode(query, convert_to_tensor=True)
        
        # Compute cosine similarities
        cosine_scores = util.cos_sim(query_embedding, self.kb_embeddings)[0]
        
        # Get top-k indices
        top_results = torch.topk(cosine_scores, k=min(top_k, len(self.knowledge_base)))
        
        results = []
        for score, idx in zip(top_results.values, top_results.indices):
            if score > 0.3: # Minimum relevance threshold
                results.append({
                    "snippet": self.knowledge_base[idx.item()]["content"],
                    "confidence": round(score.item(), 2),
                    "id": self.knowledge_base[idx.item()]["id"]
                })
                
        return results

    def add_knowledge(self, content: str, tags: Optional[List[str]] = None) -> str:
        """
        [Autonomous Learning] Dynamically adds new information to the knowledge base.
        """
        import uuid
        uid_str: str = str(uuid.uuid4()).replace("-", "")
        new_id = f"dynamic_{uid_str[:8]}"
        self.knowledge_base.append({
            "id": new_id,
            "content": content,
            "tags": tags if tags is not None else []
        })
        # Re-compute embeddings (In Vector DB this happens automatically)
        self.kb_embeddings = self.model.encode(
            [item["content"] for item in self.knowledge_base], 
            convert_to_tensor=True
        )
        return new_id
